Add Contact Form Section
biruk-bereka/PortfolioProject pull request #3
Opened 2022-04-26 18:53 UTC by biruk-bereka

#Add Contact Form Section

1.   Add contact description 
2.   Add contact form

2022-04-26 22:26 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️ 

Hi @biruk-bereka,

![AlonzoLeroneThisCloseGIF (2)](https://user-images.githubusercontent.com/50941074/165402579-8a78b905-9044-4240-9053-633dfc5db3eb.gif)
 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ Github flow is fine
✅ No Linters errors
✅ Good commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-04-26 22:26 UTC, AmaduKamara commented on index.html
> +                <textarea name="comment" placeholder="Enter text here"></textarea>
- [ ] It is always considered a good practice when it comes to securing your form data to at least make use of the minimal form validation HTML provides us. For this project, kindly make use of the required attribute for all fields in the form to prevent the form from submitting empty values in the input fields. Please fix that. 👍 

Below is the error message that was given by Form Spree for submitting empty values.

![image](https://user-images.githubusercontent.com/50941074/165401924-8a5d13f5-df64-4f8d-bf0d-a94910b684be.png)

2022-04-27 06:28 UTC, prolajumokeoni approved these changes
Hi @Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀  
- Good Pr and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- Kindly ensure that as  partners you always have balanced commits in pair programming project 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 06:28 UTC, prolajumokeoni commented on index.html
> +                <textarea name="comment" placeholder="Enter text here" required></textarea>
## OPTIONAL

- [ ] Kindly add a maximum length for textarea `maxlength="500"`, this is part of the requirements 👍🏿

2022-04-27 06:45 UTC, merged